### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [thomasluizzi/prj-rev-bwfs-dasmoto#5]
Grade: **Meets Expectations**

This project is working great! I really like how clean your HTML & CSS was to look over and determine where everything needed to be. A couple things I would change is to make sure you add alt tags to your images in order to give our users a text descriptor of the image. The other thing would be to do is remove the unnecessary `role` attributes. Next steps, I would look into media queries in order to make your pages responsive: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by thomasluizzi** [comment]
Thank you for the feedback.  I've made all of your recommended changes and I'll review these references.
